import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  // API: Expand single vibe into 4 detailed prompts
  app.post("/api/expand-prompts", async (req, res) => {
    try {
      const { vibe } = req.body;
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `Given the vibe: "${vibe}", generate 4 distinct, highly detailed and artistic prompts for an image generation AI. 
        Aim for a professional phone wallpaper aesthetic in 9:16 aspect ratio.
        Output exactly 4 lines, each being a fully expanded detailed prompt. No other text.`
      });
      
      const text = response.text || '';
      const prompts = text.split('\n').filter(p => p.trim()).slice(0, 4);
      res.json({ prompts });
    } catch (error: any) {
      console.error("Expand Error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  // API: Generate image from prompt (and optional reference)
  app.post("/api/generate-wallpaper", async (req, res) => {
    try {
      const { prompt, referenceImage } = req.body;
      const parts: any[] = [{ text: prompt }];
      
      if (referenceImage) {
        const base64Data = referenceImage.split(',')[1];
        parts.unshift({
          inlineData: {
            data: base64Data,
            mimeType: "image/png"
          }
        });
        parts[1].text = `Remix this reference image. New Vibe: ${prompt}. Maintain structure but change the mood.`;
      }

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts },
        config: {
          imageConfig: {
            aspectRatio: "9:16"
          }
        }
      });

      // Find the image part in the response
      const imagePart = response.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
      
      if (imagePart?.inlineData?.data) {
        res.json({ url: `data:image/png;base64,${imagePart.inlineData.data}` });
      } else {
        throw new Error("No image generated by model");
      }
    } catch (error: any) {
      console.error("Generate Error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
